### ISSUE TITLE
Profile screen

### ISSUE THREAD

**Issue by BorysChajdas** [Android-Guild/Picover#121]
Requires authentication.

## Basic content:
- avatar
- username
- email

More features could be added up to the developer ideas.

## Future
In the future, this screen could be extended to include user activities such as:
- liked photos
- uploaded photos
- last comments
- bio

## Tasks: 

- [x] Show user data
- [x] Update avatar in Firebase
- [x] Adjust UI add information about edit for avatar
- [x] Update user name
- [x] Handle exception
- [x] Extract same statements from updateAvatar, updateName, fetchProfile in ProfileViewModel 
- [x] Add placeholder for loading
- [x] Validate text
