### ISSUE TITLE
Use chained calls from mockk

### ISSUE THREAD

**Issue by MarekMacko** [Android-Guild/Picover#194]
https://mockk.io/#chained-calls

Remove redundant variables by using chained calls.
`listResult` is totally redundant here
```
	val listResult: ListResult = mockk {
		every { items } returns listOf(storageItem)
	}
	every { imageReference.listAll() } returns mockk {
		coEvery { await() } returns listResult
	}
```
Above can be simplified to:
```
	every { imageReference.listAll() } returns mockk {
		coEvery { await().items } returns listOf(storageItem)
	}
```
Goal of this task is to go throughout all test files and simplify then wherever possible

**TODO:**
- [x] ImagesRepositoryTest - use chained calls
- [x] PartiesRepositoryTest - use chained calls
- [x] ImagesViewModelTest - should be parameterized
- [x] #352

**Comment by michal-kucznerowicz** [comment]
Please create subtasks @MarekMacko

**Comment by MarekMacko** [comment]
> Please create subtasks @MarekMacko

Done. @kmaslowiec  and @michal-kucznerowicz I think that would be most beneficial for you to take care of.

**Comment by kmaslowiec** [comment]
> > Please create subtasks @MarekMacko
> 
> Done. @kmaslowiec and @michal-kucznerowicz I think that would be most beneficial for you to take care of.
Ok, I am taking take:
 ImagesRepositoryTest - use chained calls
 PartiesRepositoryTest - use chained calls
 See #284

**Comment by MarekMacko** [comment]
@marcinWisnia @kmaslowiec There are few places in `AuthRepositoryTest` to simplify, please take care of
