### ISSUE TITLE
Optimise app builds on CI

### ISSUE THREAD

**Issue by marcinWisnia** [Android-Guild/Picover#64]
## Description
- repeating `chmod +x gradlew` in each job is redundant, try to find a way how to get rid of it,
- run locally `./gradlew build --dry-run` to check which tasks are executed during `build` command, 
  - do we need all of them?
  - should we keep all of them in one job?

### Make more readable regex
Written `regex` after time could be vague. So we should make it more readable.

### Optimize CI
At this moment our `build job` executed more than ten minutes it should be faster.

### Add checking count of commits 
We have the rule one `pull request` one `commit` therefore we should have a job that will check if a pull request has one commit.

### Helpful Links: 
- [DRY: REUSING CODE IN GITHUB ACTIONS](https://cardinalby.github.io/blog/post/github-actions/dry-reusing-code-in-github-actions/)

## Tasks
- [x] Make more readable regex
- [x] Optimize CI
- [x] Add checking count of commits 
- [x] Use Docker image
- [x] Fix checking commit message

**Comment by BorysChajdas** [comment]
chmod +x on each job removed in: https://github.com/intive/Picover/pull/90
